apiVersion: v1
kind: Service
metadata:
  namespace: roboshop 
  name: mongodb-service
  labels:
    project: roboshop
    tier: database
    component: mongodb
spec:
  selector:
    project: roboshop
    tier: database
    component: mongodb
  ports:
    - protocol: TCP
      port: 27017 # service port
      targetPort: 27017 # container port

    