apiVersion: v1
kind: Service
metadata:
  namespace: roboshop
  name: mysql-service-headless
  labels:
    project: roboshop
    tier: database
    component: mysql
spec:
  clusterIP: None
  selector:
    project: roboshop
    tier: database
    component: mysql
  spec:
    - protocol: TCP
      port: 3306 # service port
      targetPort: 3306 # container port