apiVersion: v1
kind: Service
metadata:
  namespace: roboshop 
  name: mysql-service
  labels:
    project: roboshop
    tier: database
    component: mysql
spec:
  selector:
    project: roboshop
    tier: database
    component: mysql
  ports:
    - protocol: TCP
      port: 3306 # service port
      targetPort: 3306 # container port

    