apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    tier: database
    component: mysql
spec:
  selector:
    matchLabels:
      project: roboshop
      tier: database
      component: mysql # has to match .spec.template.metadata.labels
  serviceName: "mysql-service-headless"
  replicas: 2 # by default is 1
  template:
    metadata:
      labels:
        project: roboshop
        tier: database
        component: mysql # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: mysql
        image: "{{ .Values.statefulset.imagePath }}:{{ .Values.statefulset.imageVersion }}"
        envFrom:
        - secretRef:
            name: mysql-Secret
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs"
      resources:
        requests:
          storage: 4Gi