apiVersion: v1
kind: Service
metadata:
  namespace: roboshop 
  name: redis-service
  labels:
    project: roboshop
    tier: database
    component: redis
spec:
  selector:
    project: roboshop
    tier: database
    component: redis
  ports:
    - protocol: TCP
      port: 6379 # service port
      targetPort: 6379 # container port