apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: roboshop
  labels:
    project: roboshop
    tier: database
    component: redis
spec:
  selector:
    matchLabels:
      project: roboshop
      tier: database
      component: redis # has to match .spec.template.metadata.labels
  serviceName: "redis-service-headless"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        project: roboshop
        tier: database
        component: redis # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: redis
        image: "{{ .Values.statefulset.imagePath }}:{{ .Values.statefulset.imageVersion }}"
        volumeMounts:
        - name: redis-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs"
      resources:
        requests:
          storage: 4Gi