apiVersion: v1
kind: Service
metadata:
  namespace: roboshop 
  name: rabbitmq-service
  labels:
    project: roboshop
    tier: database
    component: rabbitmq
spec:
  selector:
    project: roboshop
    tier: database
    component: rabbitmq
  ports:
    - protocol: TCP
      port: 5672 # service port
      targetPort: 5672 # container port