
apiVersion: v1
kind: Service
metadata:
  namespace: roboshop
  name: rabbitmq-service-headless
  labels:
    project: roboshop
    tier: database
    component: rabbitmq
spec:
  clusterIP: None
  selector:
    project: roboshop
    tier: database
    component: rabbitmq
  spec:
    - protocol: TCP
      port: 5672 # service port
      targetPort: 5672 # container port