apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    tier: database
    component: rabbitmq
spec:
  selector:
    matchLabels:
      project: roboshop
      tier: database
      component: rabbitmq # has to match .spec.template.metadata.labels
  serviceName: "rabbitmq-service-headless"
  replicas: 2 # by default is 1
  template:
    metadata:
      labels:
        project: roboshop
        tier: database
        component: rabbitmq # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: rabbitmq
        image: "{{ .Values.statefulset.imagePath }}:{{ .Values.statefulset.imageVersion }}"
        envFrom:
        - secretRef:
            name: rabbitmq-secret
              
        volumeMounts:
        - name: rabbitmq-data
          mountPath: /var/lib/rabbitmq
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs"
      resources:
        requests:
          storage: 4Gi